### ISSUE TITLE
Create Component stories for autocomplete tree select

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms-components#28]
You can use data from:
`Form 1/ma provozovatele`

Do 4 different stories:

- 1. section with single-select autocomplete [DONE]
- 2. section with multi-select autocomplete [DONE]
- 3. simple question with single-select autocomplete [DONE]
- 4. simple question with multi-select autocomplete - we do not need it - this will not be solved in this ticket [WON'T BE IMPLEMENTED]

If very easy to do you can add also subquestions of ma-provozovatele in stories 1. and 2.

**Comment by VojtechLunak** [comment]
@blcham 
I found out, that the `TypeQuestionAnswer` will be always rendered in the section header. It is based on hard coded prop [`isInSectionHeader`](https://github.com/kbss-cvut/s-forms-components/blob/fed48ec79348d58ec2e3254c9a8fe46e32ede33a/src/components/SectionComponent.jsx#L86). And when I tried hardcoding the prop to `false`, it does not work as expected, at least to my imagination. With `isInSectionHeader` property set to false, the `IntelligentTreeSelect` component is still rendering in the blue block along with the section label. In the [PR preview](https://deploy-preview-27--s-forms-components-kbss.netlify.app), I did not change this behaviour, so all stories behave like `isInSectionHeader` is `true`.

I also could not make the stories work when I wanted to render single TypeQuestionAnswer component, because I still was not sure how to structure the question data, so I used the whole form and picked only data related to TypeQuestionAnswer. But it is still rendered as a child of `SForms` component.

**Comment by blcham** [comment]
> I found out, that the TypeQuestionAnswer will be always rendered in the section header

We called "TypeQuestion" question that asks about type of entity (e.g. `Provozovatel`/`Person`) that section represents. I.e. it would be confusing calling an `TypeQuestionAnswer` if it is something that is not visualized "on section".

So in case we cannot have one type of answer for both section and non-section, I would call it differently e.g. `TypeaheadTreeAnswer`. (it could be used even instead of `TypeQuestionAnswer` if we have both functionalities merged in one).

> ... because I still was not sure how to structure the question data ...

It would be nice to debug it together then, because it is quite important to clearly understand what data component needs and separate it from the rest of the form data.
